// 再興小學一年級下學期 (114-2 / 2026 Spring) 英文單字 + 每週一句 + 注音
// 資料來源：學校單字表 PDF + 每週一句 PDF
// bopo 欄位：每個漢字一段注音（空白分隔），用於 <ruby> 注音標示

const WORDS = {
  // 玩具 Toys
  "bike":        { zh: "腳踏車",   bopo: "ㄐㄧㄠˇ ㄊㄚˋ ㄔㄜ",          emoji: "🚲", category: "toys" },
  "computer":    { zh: "電腦",     bopo: "ㄉㄧㄢˋ ㄋㄠˇ",                emoji: "💻", category: "toys" },
  "game":        { zh: "遊戲",     bopo: "ㄧㄡˊ ㄒㄧˋ",                  emoji: "🎮", category: "toys" },
  "teddy bear":  { zh: "泰迪熊",   bopo: "ㄊㄞˋ ㄉㄧˊ ㄒㄩㄥˊ",          emoji: "🧸", category: "toys" },
  "robot":       { zh: "機器人",   bopo: "ㄐㄧ ㄑㄧˋ ㄖㄣˊ",             emoji: "🤖", category: "toys" },
  "kite":        { zh: "風箏",     bopo: "ㄈㄥ ㄓㄥ",                    emoji: "🪁", category: "toys" },

  // 顏色 Colors
  "red":         { zh: "紅色",     bopo: "ㄏㄨㄥˊ ㄙㄜˋ",                emoji: "🔴", category: "colors" },
  "blue":        { zh: "藍色",     bopo: "ㄌㄢˊ ㄙㄜˋ",                  emoji: "🔵", category: "colors" },
  "white":       { zh: "白色",     bopo: "ㄅㄞˊ ㄙㄜˋ",                  emoji: "⚪", category: "colors" },
  "green":       { zh: "綠色",     bopo: "ㄌㄩˋ ㄙㄜˋ",                  emoji: "🟢", category: "colors" },
  "pink":        { zh: "粉紅色",   bopo: "ㄈㄣˇ ㄏㄨㄥˊ ㄙㄜˋ",          emoji: "🌸", category: "colors" },
  "gray":        { zh: "灰色",     bopo: "ㄏㄨㄟ ㄙㄜˋ",                 emoji: "🩶", category: "colors" },
  "black":       { zh: "黑色",     bopo: "ㄏㄟ ㄙㄜˋ",                   emoji: "⚫", category: "colors" },
  "yellow":      { zh: "黃色",     bopo: "ㄏㄨㄤˊ ㄙㄜˋ",                emoji: "🟡", category: "colors" },
  "orange":      { zh: "橘色",     bopo: "ㄐㄩˊ ㄙㄜˋ",                  emoji: "🟠", category: "colors" },
  "brown":       { zh: "棕色",     bopo: "ㄗㄨㄥ ㄙㄜˋ",                 emoji: "🟤", category: "colors" },

  // 動物 Animals
  "bird":        { zh: "鳥",       bopo: "ㄋㄧㄠˇ",                       emoji: "🐦", category: "animals" },
  "rabbit":      { zh: "兔子",     bopo: "ㄊㄨˋ ㄗ˙",                    emoji: "🐰", category: "animals" },
  "turtle":      { zh: "烏龜",     bopo: "ㄨ ㄍㄨㄟ",                    emoji: "🐢", category: "animals" },
  "mouse":       { zh: "老鼠",     bopo: "ㄌㄠˇ ㄕㄨˇ",                  emoji: "🐭", category: "animals" },
  "horse":       { zh: "馬",       bopo: "ㄇㄚˇ",                         emoji: "🐴", category: "animals" },
  "snake":       { zh: "蛇",       bopo: "ㄕㄜˊ",                         emoji: "🐍", category: "animals" },
  "spider":      { zh: "蜘蛛",     bopo: "ㄓ ㄓㄨ",                      emoji: "🕷️", category: "animals" },
  "frog":        { zh: "青蛙",     bopo: "ㄑㄧㄥ ㄨㄚ",                   emoji: "🐸", category: "animals" },
  "iguana":      { zh: "鬣蜥",     bopo: "ㄌㄧㄝˋ ㄒㄧ",                  emoji: "🦎", category: "animals" },
  "hamster":     { zh: "倉鼠",     bopo: "ㄘㄤ ㄕㄨˇ",                   emoji: "🐹", category: "animals" },

  // 身體 Body
  "hair":        { zh: "頭髮",     bopo: "ㄊㄡˊ ㄈㄚˇ",                  emoji: "💇", category: "body" },
  "mouth":       { zh: "嘴巴",     bopo: "ㄗㄨㄟˇ ㄅㄚ",                  emoji: "👄", category: "body" },
  "eye":         { zh: "眼睛",     bopo: "ㄧㄢˇ ㄐㄧㄥ",                  emoji: "👁️", category: "body" },
  "ear":         { zh: "耳朵",     bopo: "ㄦˇ ㄉㄨㄛ˙",                  emoji: "👂", category: "body" },
  "nose":        { zh: "鼻子",     bopo: "ㄅㄧˊ ㄗ˙",                    emoji: "👃", category: "body" },
  "tooth/teeth": { zh: "牙齒",     bopo: "ㄧㄚˊ ㄔˇ",                    emoji: "🦷", category: "body", speak: "tooth, teeth" },
  "toe":         { zh: "腳趾",     bopo: "ㄐㄧㄠˇ ㄓˇ",                  emoji: "🦶", category: "body" },
  "finger":      { zh: "手指",     bopo: "ㄕㄡˇ ㄓˇ",                    emoji: "👆", category: "body" },
  "hand":        { zh: "手",       bopo: "ㄕㄡˇ",                         emoji: "✋", category: "body" },
  "foot/feet":   { zh: "腳",       bopo: "ㄐㄧㄠˇ",                       emoji: "🦶", category: "body", speak: "foot, feet" },
  "arm":         { zh: "手臂",     bopo: "ㄕㄡˇ ㄅㄧˋ",                   emoji: "💪", category: "body" },
  "leg":         { zh: "腿",       bopo: "ㄊㄨㄟˇ",                       emoji: "🦵", category: "body" },

  // 地方 Places
  "school":      { zh: "學校",     bopo: "ㄒㄩㄝˊ ㄒㄧㄠˋ",               emoji: "🏫", category: "places" },
  "mall":        { zh: "購物中心", bopo: "ㄍㄡˋ ㄨˋ ㄓㄨㄥ ㄒㄧㄣ",       emoji: "🏬", category: "places" },
  "pool":        { zh: "游泳池",   bopo: "ㄧㄡˊ ㄩㄥˇ ㄔˊ",              emoji: "🏊", category: "places" },
  "stadium":     { zh: "體育場",   bopo: "ㄊㄧˇ ㄩˋ ㄔㄤˇ",              emoji: "🏟️", category: "places" },
  "lake":        { zh: "湖",       bopo: "ㄏㄨˊ",                         emoji: "🏞️", category: "places" },
  "beach":       { zh: "海灘",     bopo: "ㄏㄞˇ ㄊㄢ",                    emoji: "🏖️", category: "places" },
  "park":        { zh: "公園",     bopo: "ㄍㄨㄥ ㄩㄢˊ",                  emoji: "🌳", category: "places" },

  // 大自然 Nature
  "tree":        { zh: "樹",       bopo: "ㄕㄨˋ",                         emoji: "🌳", category: "nature" },
  "river":       { zh: "河",       bopo: "ㄏㄜˊ",                         emoji: "🏞️", category: "nature" },
  "mountain":    { zh: "山",       bopo: "ㄕㄢ",                          emoji: "⛰️", category: "nature" },
  "flower":      { zh: "花",       bopo: "ㄏㄨㄚ",                        emoji: "🌺", category: "nature" },

  // 水果 Fruits
  "banana":      { zh: "香蕉",     bopo: "ㄒㄧㄤ ㄐㄧㄠ",                  emoji: "🍌", category: "fruits" },
  "watermelon":  { zh: "西瓜",     bopo: "ㄒㄧ ㄍㄨㄚ",                    emoji: "🍉", category: "fruits" },
  "pineapple":   { zh: "鳳梨",     bopo: "ㄈㄥˋ ㄌㄧˊ",                  emoji: "🍍", category: "fruits" },
  "pear":        { zh: "梨子",     bopo: "ㄌㄧˊ ㄗ˙",                    emoji: "🍐", category: "fruits" },

  // 數字 Numbers
  "eleven":      { zh: "十一",     bopo: "ㄕˊ ㄧ",                       emoji: "1️⃣1️⃣", category: "numbers" },
  "twelve":      { zh: "十二",     bopo: "ㄕˊ ㄦˋ",                      emoji: "1️⃣2️⃣", category: "numbers" },
  "thirteen":    { zh: "十三",     bopo: "ㄕˊ ㄙㄢ",                     emoji: "1️⃣3️⃣", category: "numbers" },
  "fifteen":     { zh: "十五",     bopo: "ㄕˊ ㄨˇ",                      emoji: "1️⃣5️⃣", category: "numbers" },
  "twenty":      { zh: "二十",     bopo: "ㄦˋ ㄕˊ",                      emoji: "2️⃣0️⃣", category: "numbers" },

  // 家具 Furniture
  "bed":         { zh: "床",       bopo: "ㄔㄨㄤˊ",                      emoji: "🛏️", category: "furniture" },
  "sofa":        { zh: "沙發",     bopo: "ㄕㄚ ㄈㄚ",                    emoji: "🛋️", category: "furniture" },
  "closet":      { zh: "衣櫃",     bopo: "ㄧ ㄍㄨㄟˋ",                   emoji: "🚪", category: "furniture" },
  "chair":       { zh: "椅子",     bopo: "ㄧˇ ㄗ˙",                     emoji: "🪑", category: "furniture" },
  "table":       { zh: "桌子",     bopo: "ㄓㄨㄛ ㄗ˙",                   emoji: "🪟", category: "furniture" },

  // 房間 Rooms
  "bedroom":     { zh: "臥室",     bopo: "ㄨㄛˋ ㄕˋ",                    emoji: "🛏️", category: "rooms" },
  "bathroom":    { zh: "浴室",     bopo: "ㄩˋ ㄕˋ",                      emoji: "🛁", category: "rooms" },
  "garage":      { zh: "車庫",     bopo: "ㄔㄜ ㄎㄨˋ",                   emoji: "🚗", category: "rooms" },
  "yard":        { zh: "院子",     bopo: "ㄩㄢˋ ㄗ˙",                    emoji: "🌿", category: "rooms" },
  "living room": { zh: "客廳",     bopo: "ㄎㄜˋ ㄊㄧㄥ",                  emoji: "🛋️", category: "rooms" },
  "kitchen":     { zh: "廚房",     bopo: "ㄔㄨˊ ㄈㄤˊ",                  emoji: "🍳", category: "rooms" },
};

const WEEKS = [
  { num: 1,  dateRange: "1/20-1/22", start: "2026-01-20", end: "2026-01-22", progress: "Review 1-4",         words: ["bike","computer","game","teddy bear","robot"] },
  { num: 2,  dateRange: "2/15-2/21", start: "2026-02-15", end: "2026-02-21", progress: "Review 1-4",         words: ["kite","red","blue","white"] },
  { num: 3,  dateRange: "2/22-2/28", start: "2026-02-22", end: "2026-02-28", progress: "Unit 5",             words: ["green","pink","gray","black"] },
  { num: 4,  dateRange: "3/1-3/7",   start: "2026-03-01", end: "2026-03-07", progress: "Unit 5",             words: ["yellow","orange","brown","bird"] },
  { num: 5,  dateRange: "3/8-3/14",  start: "2026-03-08", end: "2026-03-14", progress: "Unit 5/6 Quiz",      words: ["rabbit","turtle","mouse","horse"] },
  { num: 6,  dateRange: "3/15-3/21", start: "2026-03-15", end: "2026-03-21", progress: "Unit 6",             words: ["snake","spider","frog","iguana"] },
  { num: 7,  dateRange: "3/22-3/28", start: "2026-03-22", end: "2026-03-28", progress: "Unit 6/7 Quiz",      words: ["hamster","hair","mouth","eye"] },
  { num: 8,  dateRange: "3/29-4/4",  start: "2026-03-29", end: "2026-04-04", progress: "Unit 7",             words: ["ear","nose","tooth/teeth","toe"] },
  { num: 9,  dateRange: "4/5-4/11",  start: "2026-04-05", end: "2026-04-11", progress: "Unit 7/8 Quiz",      words: ["finger","hand","foot/feet","arm"] },
  { num: 10, dateRange: "4/12-4/18", start: "2026-04-12", end: "2026-04-18", progress: "Midterm (Unit 5-7)", words: [] },
  { num: 11, dateRange: "4/19-4/25", start: "2026-04-19", end: "2026-04-25", progress: "Unit 8",             words: ["leg","school","mall","pool"] },
  { num: 12, dateRange: "4/26-5/2",  start: "2026-04-26", end: "2026-05-02", progress: "Unit 8",             words: ["stadium","lake","beach","park"] },
  { num: 13, dateRange: "5/3-5/9",   start: "2026-05-03", end: "2026-05-09", progress: "Unit 8/9 Quiz",      words: ["tree","river","mountain","flower"] },
  { num: 14, dateRange: "5/10-5/16", start: "2026-05-10", end: "2026-05-16", progress: "Unit 9",             words: ["banana","watermelon","pineapple","pear"] },
  { num: 15, dateRange: "5/17-5/23", start: "2026-05-17", end: "2026-05-23", progress: "Unit 9",             words: ["eleven","twelve","thirteen","fifteen"] },
  { num: 16, dateRange: "5/24-5/30", start: "2026-05-24", end: "2026-05-30", progress: "Unit 9 Quiz",        words: ["twenty","bed","sofa","closet"] },
  { num: 17, dateRange: "5/31-6/6",  start: "2026-05-31", end: "2026-06-06", progress: "Unit 10",            words: ["chair","table","bedroom","bathroom"] },
  { num: 18, dateRange: "6/7-6/13",  start: "2026-06-07", end: "2026-06-13", progress: "Unit 10",            words: ["garage","yard","living room","kitchen"] },
  { num: 19, dateRange: "6/14-6/20", start: "2026-06-14", end: "2026-06-20", progress: "Review Unit 8-10",   words: [] },
  { num: 20, dateRange: "6/21-6/27", start: "2026-06-21", end: "2026-06-27", progress: "Final (Unit 8-10)",  words: [] },
  { num: 21, dateRange: "6/28-6/30", start: "2026-06-28", end: "2026-06-30", progress: "Review Unit 1-10",   words: [] },
];

// 單元組 Units（依教科書 Unit 5-10 + 學期 1-4 複習）— 用於自選單元考試
const UNITS = [
  { id: "review-1-4", name: "Unit 1-4 複習", emoji: "📦", color: "#e0e0e0",
    bopo: "ㄈㄨˋ ㄒㄧˊ",
    words: ["bike","computer","game","teddy bear","robot","kite","red","blue","white"] },
  { id: "unit-5", name: "Unit 5 顏色", emoji: "🎨", color: "#ffe5b4",
    bopo: "ㄧㄢˊ ㄙㄜˋ",
    words: ["green","pink","gray","black","yellow","orange","brown","bird"] },
  { id: "unit-6", name: "Unit 6 動物", emoji: "🐰", color: "#d0f4de",
    bopo: "ㄉㄨㄥˋ ㄨˋ",
    words: ["rabbit","turtle","mouse","horse","snake","spider","frog","iguana","hamster"] },
  { id: "unit-7", name: "Unit 7 身體", emoji: "👀", color: "#fcd5ce",
    bopo: "ㄕㄣ ㄊㄧˇ",
    words: ["hair","mouth","eye","ear","nose","tooth/teeth","toe","finger","hand","foot/feet","arm","leg"] },
  { id: "unit-8", name: "Unit 8 地方", emoji: "🏫", color: "#cdeafe",
    bopo: "ㄉㄧˋ ㄈㄤ",
    words: ["school","mall","pool","stadium","lake","beach","park","tree","river","mountain","flower"] },
  { id: "unit-9", name: "Unit 9 水果·數字·家具", emoji: "🍌", color: "#fff5ba",
    bopo: "ㄕㄨㄟˇ ㄍㄨㄛˇ",
    words: ["banana","watermelon","pineapple","pear","eleven","twelve","thirteen","fifteen","twenty","bed","sofa","closet"] },
  { id: "unit-10", name: "Unit 10 房間", emoji: "🚪", color: "#c1e7e3",
    bopo: "ㄈㄤˊ ㄐㄧㄢ",
    words: ["chair","table","bedroom","bathroom","garage","yard","living room","kitchen"] },
];

const SENTENCES = [
  { week: 1,  en: "I feel great today.",                zh: "我今天覺得很好",
    bopo: "ㄨㄛˇ ㄐㄧㄣ ㄊㄧㄢ ㄐㄩㄝˊ ㄉㄜ˙ ㄏㄣˇ ㄏㄠˇ" },
  { week: 2,  en: "I don't feel well.",                 zh: "我覺得不太舒服",
    bopo: "ㄨㄛˇ ㄐㄩㄝˊ ㄉㄜ˙ ㄅㄨˊ ㄊㄞˋ ㄕㄨ ㄈㄨˊ" },
  { week: 3,  en: "My ___ hurts.",                      zh: "我的___痛",
    bopo: "ㄨㄛˇ ㄉㄜ˙ ㄊㄨㄥˋ",
    blank: { hint: "身體部位", suggest: ["head","tooth","arm","leg","foot","hand","ear","eye"] } },
  { week: 4,  en: "I feel okay now.",                   zh: "我現在覺得還好",
    bopo: "ㄨㄛˇ ㄒㄧㄢˋ ㄗㄞˋ ㄐㄩㄝˊ ㄉㄜ˙ ㄏㄞˊ ㄏㄠˇ" },
  { week: 5,  en: "Can I come in?",                     zh: "我可以進來嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄐㄧㄣˋ ㄌㄞˊ ㄇㄚ" },
  { week: 6,  en: "Can I go to my locker?",             zh: "我可以去置物櫃嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄓˋ ㄨˋ ㄍㄨㄟˋ ㄇㄚ" },
  { week: 7,  en: "Can ___ help me?",                   zh: "___可以幫我嗎?",
    bopo: "ㄎㄜˇ ㄧˇ ㄅㄤ ㄨㄛˇ ㄇㄚ",
    blank: { hint: "人", suggest: ["you","Mom","Dad","Teacher","he","she"] } },
  { week: 8,  en: "Can I go to the restroom?",          zh: "我可以去廁所嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄘㄜˋ ㄙㄨㄛˇ ㄇㄚ" },
  { week: 9,  en: "Can I go get some water?",           zh: "我可以去拿水嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄋㄚˊ ㄕㄨㄟˇ ㄇㄚ" },
  { week: 10, en: "Can ___ go with me?",                zh: "___可以跟我去嗎?",
    bopo: "ㄎㄜˇ ㄧˇ ㄍㄣ ㄨㄛˇ ㄑㄩˋ ㄇㄚ",
    blank: { hint: "人", suggest: ["you","he","she","Mom","Dad"] } },
  { week: 11, en: "Just a minute.",                     zh: "等一下",
    bopo: "ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ" },
  { week: 12, en: "I put it away.",                     zh: "我收起來了",
    bopo: "ㄨㄛˇ ㄕㄡ ㄑㄧˇ ㄌㄞˊ ㄌㄜ˙" },
  { week: 13, en: "Teacher, can I help you?",           zh: "老師，我可以幫你嗎?",
    bopo: "ㄌㄠˇ ㄕ ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄅㄤ ㄋㄧˇ ㄇㄚ" },
  { week: 14, en: "I want to help!",                    zh: "我想要幫忙!",
    bopo: "ㄨㄛˇ ㄒㄧㄤˇ ㄧㄠˋ ㄅㄤ ㄇㄤˊ" },
  { week: 15, en: "I have a question.",                 zh: "我有一個問題",
    bopo: "ㄨㄛˇ ㄧㄡˇ ㄧˊ ㄍㄜ˙ ㄨㄣˋ ㄊㄧˊ" },
  { week: 16, en: "Where are we going?",                zh: "我們要去哪裡?",
    bopo: "ㄨㄛˇ ㄇㄣ˙ ㄧㄠˋ ㄑㄩˋ ㄋㄚˇ ㄌㄧˇ" },
  { week: 17, en: "Help, ___ hit me!",                  zh: "救命，___打我!",
    bopo: "ㄐㄧㄡˋ ㄇㄧㄥˋ ㄉㄚˇ ㄨㄛˇ",
    blank: { hint: "人", suggest: ["he","she","they","someone"] } },
  { week: 18, en: "He / She took my ___.",              zh: "他/她拿了我的___",
    bopo: "ㄊㄚ ㄊㄚ ㄋㄚˊ ㄌㄜ˙ ㄨㄛˇ ㄉㄜ˙",
    blank: { hint: "東西", suggest: ["pencil","book","bag","toy","game"] } },
  { week: 19, en: "It's not my fault.",                 zh: "不是我的錯",
    bopo: "ㄅㄨˊ ㄕˋ ㄨㄛˇ ㄉㄜ˙ ㄘㄨㄛˋ" },
  { week: 20, en: "I'm sorry. I didn't mean to ___.",   zh: "對不起，我不是故意___",
    bopo: "ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ ㄨㄛˇ ㄅㄨˊ ㄕˋ ㄍㄨˋ ㄧˋ",
    blank: { hint: "動作", suggest: ["do it","push you","break it","hurt you"] } },
];

const CATEGORIES = [
  { id: "toys",      name: "玩具",     bopo: "ㄨㄢˊ ㄐㄩˋ",          nameEn: "Toys",      emoji: "🧸", color: "#ffd6e0",
    words: ["bike","computer","game","teddy bear","robot","kite"] },
  { id: "colors",    name: "顏色",     bopo: "ㄧㄢˊ ㄙㄜˋ",          nameEn: "Colors",    emoji: "🎨", color: "#ffe5b4",
    words: ["red","blue","white","green","pink","gray","black","yellow","orange","brown"] },
  { id: "animals",   name: "動物",     bopo: "ㄉㄨㄥˋ ㄨˋ",          nameEn: "Animals",   emoji: "🐰", color: "#d0f4de",
    words: ["bird","rabbit","turtle","mouse","horse","snake","spider","frog","iguana","hamster"] },
  { id: "body",      name: "身體",     bopo: "ㄕㄣ ㄊㄧˇ",           nameEn: "Body",      emoji: "👀", color: "#fcd5ce",
    words: ["hair","mouth","eye","ear","nose","tooth/teeth","toe","finger","hand","foot/feet","arm","leg"] },
  { id: "places",    name: "地方",     bopo: "ㄉㄧˋ ㄈㄤ",           nameEn: "Places",    emoji: "🏫", color: "#cdeafe",
    words: ["school","mall","pool","stadium","lake","beach","park"] },
  { id: "nature",    name: "大自然",   bopo: "ㄉㄚˋ ㄗˋ ㄖㄢˊ",      nameEn: "Nature",    emoji: "🌳", color: "#b8e0d2",
    words: ["tree","river","mountain","flower"] },
  { id: "fruits",    name: "水果",     bopo: "ㄕㄨㄟˇ ㄍㄨㄛˇ",       nameEn: "Fruits",    emoji: "🍌", color: "#fff5ba",
    words: ["banana","watermelon","pineapple","pear"] },
  { id: "numbers",   name: "數字",     bopo: "ㄕㄨˋ ㄗˋ",           nameEn: "Numbers",   emoji: "🔢", color: "#e0c3fc",
    words: ["eleven","twelve","thirteen","fifteen","twenty"] },
  { id: "furniture", name: "家具",     bopo: "ㄐㄧㄚ ㄐㄩˋ",          nameEn: "Furniture", emoji: "🛏️", color: "#f5d0c5",
    words: ["bed","sofa","closet","chair","table"] },
  { id: "rooms",     name: "房間",     bopo: "ㄈㄤˊ ㄐㄧㄢ",          nameEn: "Rooms",     emoji: "🚪", color: "#c1e7e3",
    words: ["bedroom","bathroom","garage","yard","living room","kitchen"] },
];

// ADHD 友善 — 動一動小提示，每答對 N 題彈一次
const MOVEMENT_BREAKS = [
  { emoji: "🤸", text: "站起來跳 5 下！" },
  { emoji: "🙌", text: "雙手舉高，伸個懶腰～" },
  { emoji: "👏", text: "拍手 5 下，慶祝一下！" },
  { emoji: "🦵", text: "原地踏步 10 下！" },
  { emoji: "🌬️", text: "深呼吸 3 次：吸～呼～" },
  { emoji: "💃", text: "扭一扭屁股 10 秒！" },
  { emoji: "👀", text: "眼睛左右轉，看看遠方～" },
  { emoji: "🤲", text: "把手搓熱，蓋住眼睛 5 秒" },
];
