// 再興小學一年級下學期 (114-2 / 2026 Spring) 英文單字 + 每週一句 + 注音
// 資料來源：學校單字表 PDF + 每週一句 PDF
// bopo 欄位：每個漢字一段注音（空白分隔），用於 <ruby> 注音標示

const WORDS = {
  // 玩具 Toys
  "bike":        { zh: "腳踏車",   bopo: "ㄐㄧㄠˇ ㄊㄚˋ ㄔㄜ",          emoji: "🚲", category: "toys" },
  "computer":    { zh: "電腦",     bopo: "ㄉㄧㄢˋ ㄋㄠˇ",                emoji: "💻", category: "toys" },
  "game":        { zh: "遊戲",     bopo: "ㄧㄡˊ ㄒㄧˋ",                  emoji: "🎮", category: "toys" },
  "teddy bear":  { zh: "泰迪熊",   bopo: "ㄊㄞˋ ㄉㄧˊ ㄒㄩㄥˊ",          emoji: "🧸", category: "toys" },
  "robot":       { zh: "機器人",   bopo: "ㄐㄧ ㄑㄧˋ ㄖㄣˊ",             emoji: "🤖", category: "toys" },
  "kite":        { zh: "風箏",     bopo: "ㄈㄥ ㄓㄥ",                    emoji: "🪁", category: "toys" },

  // 顏色 Colors
  "red":         { zh: "紅色",     bopo: "ㄏㄨㄥˊ ㄙㄜˋ",                emoji: "🔴", category: "colors" },
  "blue":        { zh: "藍色",     bopo: "ㄌㄢˊ ㄙㄜˋ",                  emoji: "🔵", category: "colors" },
  "white":       { zh: "白色",     bopo: "ㄅㄞˊ ㄙㄜˋ",                  emoji: "⚪", category: "colors" },
  "green":       { zh: "綠色",     bopo: "ㄌㄩˋ ㄙㄜˋ",                  emoji: "🟢", category: "colors" },
  "pink":        { zh: "粉紅色",   bopo: "ㄈㄣˇ ㄏㄨㄥˊ ㄙㄜˋ",          emoji: "🌸", category: "colors" },
  "gray":        { zh: "灰色",     bopo: "ㄏㄨㄟ ㄙㄜˋ",                 emoji: "🩶", category: "colors" },
  "black":       { zh: "黑色",     bopo: "ㄏㄟ ㄙㄜˋ",                   emoji: "⚫", category: "colors" },
  "yellow":      { zh: "黃色",     bopo: "ㄏㄨㄤˊ ㄙㄜˋ",                emoji: "🟡", category: "colors" },
  "orange":      { zh: "橘色",     bopo: "ㄐㄩˊ ㄙㄜˋ",                  emoji: "🟠", category: "colors" },
  "brown":       { zh: "棕色",     bopo: "ㄗㄨㄥ ㄙㄜˋ",                 emoji: "🟤", category: "colors" },

  // 動物 Animals
  "bird":        { zh: "鳥",       bopo: "ㄋㄧㄠˇ",                       emoji: "🐦", category: "animals" },
  "rabbit":      { zh: "兔子",     bopo: "ㄊㄨˋ ㄗ˙",                    emoji: "🐰", category: "animals" },
  "turtle":      { zh: "烏龜",     bopo: "ㄨ ㄍㄨㄟ",                    emoji: "🐢", category: "animals" },
  "mouse":       { zh: "老鼠",     bopo: "ㄌㄠˇ ㄕㄨˇ",                  emoji: "🐭", category: "animals" },
  "horse":       { zh: "馬",       bopo: "ㄇㄚˇ",                         emoji: "🐴", category: "animals" },
  "snake":       { zh: "蛇",       bopo: "ㄕㄜˊ",                         emoji: "🐍", category: "animals" },
  "spider":      { zh: "蜘蛛",     bopo: "ㄓ ㄓㄨ",                      emoji: "🕷️", category: "animals" },
  "frog":        { zh: "青蛙",     bopo: "ㄑㄧㄥ ㄨㄚ",                   emoji: "🐸", category: "animals" },
  "iguana":      { zh: "鬣蜥",     bopo: "ㄌㄧㄝˋ ㄒㄧ",                  emoji: "🦎", category: "animals" },
  "hamster":     { zh: "倉鼠",     bopo: "ㄘㄤ ㄕㄨˇ",                   emoji: "🐹", category: "animals" },

  // 身體 Body
  "hair":        { zh: "頭髮",     bopo: "ㄊㄡˊ ㄈㄚˇ",                  emoji: "💇", category: "body" },
  "mouth":       { zh: "嘴巴",     bopo: "ㄗㄨㄟˇ ㄅㄚ",                  emoji: "👄", category: "body" },
  "eye":         { zh: "眼睛",     bopo: "ㄧㄢˇ ㄐㄧㄥ",                  emoji: "👁️", category: "body" },
  "ear":         { zh: "耳朵",     bopo: "ㄦˇ ㄉㄨㄛ˙",                  emoji: "👂", category: "body" },
  "nose":        { zh: "鼻子",     bopo: "ㄅㄧˊ ㄗ˙",                    emoji: "👃", category: "body" },
  "tooth/teeth": { zh: "牙齒",     bopo: "ㄧㄚˊ ㄔˇ",                    emoji: "🦷", category: "body", speak: "tooth, teeth" },
  "toe":         { zh: "腳趾",     bopo: "ㄐㄧㄠˇ ㄓˇ",                  emoji: "🦶", category: "body" },
  "finger":      { zh: "手指",     bopo: "ㄕㄡˇ ㄓˇ",                    emoji: "👆", category: "body" },
  "hand":        { zh: "手",       bopo: "ㄕㄡˇ",                         emoji: "✋", category: "body" },
  "foot/feet":   { zh: "腳",       bopo: "ㄐㄧㄠˇ",                       emoji: "🦶", category: "body", speak: "foot, feet" },
  "arm":         { zh: "手臂",     bopo: "ㄕㄡˇ ㄅㄧˋ",                   emoji: "💪", category: "body" },
  "leg":         { zh: "腿",       bopo: "ㄊㄨㄟˇ",                       emoji: "🦵", category: "body" },

  // 地方 Places
  "school":      { zh: "學校",     bopo: "ㄒㄩㄝˊ ㄒㄧㄠˋ",               emoji: "🏫", category: "places" },
  "mall":        { zh: "購物中心", bopo: "ㄍㄡˋ ㄨˋ ㄓㄨㄥ ㄒㄧㄣ",       emoji: "🏬", category: "places" },
  "pool":        { zh: "游泳池",   bopo: "ㄧㄡˊ ㄩㄥˇ ㄔˊ",              emoji: "🏊", category: "places" },
  "stadium":     { zh: "體育場",   bopo: "ㄊㄧˇ ㄩˋ ㄔㄤˇ",              emoji: "🏟️", category: "places" },
  "lake":        { zh: "湖",       bopo: "ㄏㄨˊ",                         emoji: "🏞️", category: "places" },
  "beach":       { zh: "海灘",     bopo: "ㄏㄞˇ ㄊㄢ",                    emoji: "🏖️", category: "places" },
  "park":        { zh: "公園",     bopo: "ㄍㄨㄥ ㄩㄢˊ",                  emoji: "🌳", category: "places" },

  // 大自然 Nature
  "tree":        { zh: "樹",       bopo: "ㄕㄨˋ",                         emoji: "🌳", category: "nature" },
  "river":       { zh: "河",       bopo: "ㄏㄜˊ",                         emoji: "🏞️", category: "nature" },
  "mountain":    { zh: "山",       bopo: "ㄕㄢ",                          emoji: "⛰️", category: "nature" },
  "flower":      { zh: "花",       bopo: "ㄏㄨㄚ",                        emoji: "🌺", category: "nature" },

  // 水果 Fruits
  "banana":      { zh: "香蕉",     bopo: "ㄒㄧㄤ ㄐㄧㄠ",                  emoji: "🍌", category: "fruits" },
  "watermelon":  { zh: "西瓜",     bopo: "ㄒㄧ ㄍㄨㄚ",                    emoji: "🍉", category: "fruits" },
  "pineapple":   { zh: "鳳梨",     bopo: "ㄈㄥˋ ㄌㄧˊ",                  emoji: "🍍", category: "fruits" },
  "pear":        { zh: "梨子",     bopo: "ㄌㄧˊ ㄗ˙",                    emoji: "🍐", category: "fruits" },

  // 數字 Numbers
  "eleven":      { zh: "十一",     bopo: "ㄕˊ ㄧ",                       emoji: "1️⃣1️⃣", category: "numbers" },
  "twelve":      { zh: "十二",     bopo: "ㄕˊ ㄦˋ",                      emoji: "1️⃣2️⃣", category: "numbers" },
  "thirteen":    { zh: "十三",     bopo: "ㄕˊ ㄙㄢ",                     emoji: "1️⃣3️⃣", category: "numbers" },
  "fifteen":     { zh: "十五",     bopo: "ㄕˊ ㄨˇ",                      emoji: "1️⃣5️⃣", category: "numbers" },
  "twenty":      { zh: "二十",     bopo: "ㄦˋ ㄕˊ",                      emoji: "2️⃣0️⃣", category: "numbers" },

  // 家具 Furniture
  "bed":         { zh: "床",       bopo: "ㄔㄨㄤˊ",                      emoji: "🛏️", category: "furniture" },
  "sofa":        { zh: "沙發",     bopo: "ㄕㄚ ㄈㄚ",                    emoji: "🛋️", category: "furniture" },
  "closet":      { zh: "衣櫃",     bopo: "ㄧ ㄍㄨㄟˋ",                   emoji: "🚪", category: "furniture" },
  "chair":       { zh: "椅子",     bopo: "ㄧˇ ㄗ˙",                     emoji: "🪑", category: "furniture" },
  "table":       { zh: "桌子",     bopo: "ㄓㄨㄛ ㄗ˙",                   emoji: "🪟", category: "furniture" },

  // 房間 Rooms
  "bedroom":     { zh: "臥室",     bopo: "ㄨㄛˋ ㄕˋ",                    emoji: "🛏️", category: "rooms" },
  "bathroom":    { zh: "浴室",     bopo: "ㄩˋ ㄕˋ",                      emoji: "🛁", category: "rooms" },
  "garage":      { zh: "車庫",     bopo: "ㄔㄜ ㄎㄨˋ",                   emoji: "🚗", category: "rooms" },
  "yard":        { zh: "院子",     bopo: "ㄩㄢˋ ㄗ˙",                    emoji: "🌿", category: "rooms" },
  "living room": { zh: "客廳",     bopo: "ㄎㄜˋ ㄊㄧㄥ",                  emoji: "🛋️", category: "rooms" },
  "kitchen":     { zh: "廚房",     bopo: "ㄔㄨˊ ㄈㄤˊ",                  emoji: "🍳", category: "rooms" },
};

const WEEKS = [
  { num: 1,  dateRange: "1/20-1/22", start: "2026-01-20", end: "2026-01-22", progress: "Review 1-4",         words: ["bike","computer","game","teddy bear","robot"] },
  { num: 2,  dateRange: "2/15-2/21", start: "2026-02-15", end: "2026-02-21", progress: "Review 1-4",         words: ["kite","red","blue","white"] },
  { num: 3,  dateRange: "2/22-2/28", start: "2026-02-22", end: "2026-02-28", progress: "Unit 5",             words: ["green","pink","gray","black"] },
  { num: 4,  dateRange: "3/1-3/7",   start: "2026-03-01", end: "2026-03-07", progress: "Unit 5",             words: ["yellow","orange","brown","bird"] },
  { num: 5,  dateRange: "3/8-3/14",  start: "2026-03-08", end: "2026-03-14", progress: "Unit 5/6 Quiz",      words: ["rabbit","turtle","mouse","horse"] },
  { num: 6,  dateRange: "3/15-3/21", start: "2026-03-15", end: "2026-03-21", progress: "Unit 6",             words: ["snake","spider","frog","iguana"] },
  { num: 7,  dateRange: "3/22-3/28", start: "2026-03-22", end: "2026-03-28", progress: "Unit 6/7 Quiz",      words: ["hamster","hair","mouth","eye"] },
  { num: 8,  dateRange: "3/29-4/4",  start: "2026-03-29", end: "2026-04-04", progress: "Unit 7",             words: ["ear","nose","tooth/teeth","toe"] },
  { num: 9,  dateRange: "4/5-4/11",  start: "2026-04-05", end: "2026-04-11", progress: "Unit 7/8 Quiz",      words: ["finger","hand","foot/feet","arm"] },
  { num: 10, dateRange: "4/12-4/18", start: "2026-04-12", end: "2026-04-18", progress: "Midterm (Unit 5-7)", words: [] },
  { num: 11, dateRange: "4/19-4/25", start: "2026-04-19", end: "2026-04-25", progress: "Unit 8",             words: ["leg","school","mall","pool"] },
  { num: 12, dateRange: "4/26-5/2",  start: "2026-04-26", end: "2026-05-02", progress: "Unit 8",             words: ["stadium","lake","beach","park"] },
  { num: 13, dateRange: "5/3-5/9",   start: "2026-05-03", end: "2026-05-09", progress: "Unit 8/9 Quiz",      words: ["tree","river","mountain","flower"] },
  { num: 14, dateRange: "5/10-5/16", start: "2026-05-10", end: "2026-05-16", progress: "Unit 9",             words: ["banana","watermelon","pineapple","pear"] },
  { num: 15, dateRange: "5/17-5/23", start: "2026-05-17", end: "2026-05-23", progress: "Unit 9",             words: ["eleven","twelve","thirteen","fifteen"] },
  { num: 16, dateRange: "5/24-5/30", start: "2026-05-24", end: "2026-05-30", progress: "Unit 9 Quiz",        words: ["twenty","bed","sofa","closet"] },
  { num: 17, dateRange: "5/31-6/6",  start: "2026-05-31", end: "2026-06-06", progress: "Unit 10",            words: ["chair","table","bedroom","bathroom"] },
  { num: 18, dateRange: "6/7-6/13",  start: "2026-06-07", end: "2026-06-13", progress: "Unit 10",            words: ["garage","yard","living room","kitchen"] },
  { num: 19, dateRange: "6/14-6/20", start: "2026-06-14", end: "2026-06-20", progress: "Review Unit 8-10",   words: [] },
  { num: 20, dateRange: "6/21-6/27", start: "2026-06-21", end: "2026-06-27", progress: "Final (Unit 8-10)",  words: [] },
  { num: 21, dateRange: "6/28-6/30", start: "2026-06-28", end: "2026-06-30", progress: "Review Unit 1-10",   words: [] },
];

// 單元組 Units（依教科書 Unit 5-10 + 學期 1-4 複習）— 用於自選單元考試
const UNITS = [
  { id: "review-1-4", name: "Unit 1-4 複習", emoji: "📦", color: "#e0e0e0",
    bopo: "ㄈㄨˋ ㄒㄧˊ",
    words: ["bike","computer","game","teddy bear","robot","kite","red","blue","white"] },
  { id: "unit-5", name: "Unit 5 顏色", emoji: "🎨", color: "#ffe5b4",
    bopo: "ㄧㄢˊ ㄙㄜˋ",
    words: ["green","pink","gray","black","yellow","orange","brown","bird"] },
  { id: "unit-6", name: "Unit 6 動物", emoji: "🐰", color: "#d0f4de",
    bopo: "ㄉㄨㄥˋ ㄨˋ",
    words: ["rabbit","turtle","mouse","horse","snake","spider","frog","iguana","hamster"] },
  { id: "unit-7", name: "Unit 7 身體", emoji: "👀", color: "#fcd5ce",
    bopo: "ㄕㄣ ㄊㄧˇ",
    words: ["hair","mouth","eye","ear","nose","tooth/teeth","toe","finger","hand","foot/feet","arm","leg"] },
  { id: "unit-8", name: "Unit 8 地方", emoji: "🏫", color: "#cdeafe",
    bopo: "ㄉㄧˋ ㄈㄤ",
    words: ["school","mall","pool","stadium","lake","beach","park","tree","river","mountain","flower"] },
  { id: "unit-9", name: "Unit 9 水果·數字·家具", emoji: "🍌", color: "#fff5ba",
    bopo: "ㄕㄨㄟˇ ㄍㄨㄛˇ",
    words: ["banana","watermelon","pineapple","pear","eleven","twelve","thirteen","fifteen","twenty","bed","sofa","closet"] },
  { id: "unit-10", name: "Unit 10 房間", emoji: "🚪", color: "#c1e7e3",
    bopo: "ㄈㄤˊ ㄐㄧㄢ",
    words: ["chair","table","bedroom","bathroom","garage","yard","living room","kitchen"] },
];

const SENTENCES = [
  { week: 1,  en: "I feel great today.",                zh: "我今天覺得很好",
    bopo: "ㄨㄛˇ ㄐㄧㄣ ㄊㄧㄢ ㄐㄩㄝˊ ㄉㄜ˙ ㄏㄣˇ ㄏㄠˇ" },
  { week: 2,  en: "I don't feel well.",                 zh: "我覺得不太舒服",
    bopo: "ㄨㄛˇ ㄐㄩㄝˊ ㄉㄜ˙ ㄅㄨˊ ㄊㄞˋ ㄕㄨ ㄈㄨˊ" },
  { week: 3,  en: "My ___ hurts.",                      zh: "我的___痛",
    bopo: "ㄨㄛˇ ㄉㄜ˙ ㄊㄨㄥˋ",
    blank: { hint: "身體部位", suggest: ["head","tooth","arm","leg","foot","hand","ear","eye"] } },
  { week: 4,  en: "I feel okay now.",                   zh: "我現在覺得還好",
    bopo: "ㄨㄛˇ ㄒㄧㄢˋ ㄗㄞˋ ㄐㄩㄝˊ ㄉㄜ˙ ㄏㄞˊ ㄏㄠˇ" },
  { week: 5,  en: "Can I come in?",                     zh: "我可以進來嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄐㄧㄣˋ ㄌㄞˊ ㄇㄚ" },
  { week: 6,  en: "Can I go to my locker?",             zh: "我可以去置物櫃嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄓˋ ㄨˋ ㄍㄨㄟˋ ㄇㄚ" },
  { week: 7,  en: "Can ___ help me?",                   zh: "___可以幫我嗎?",
    bopo: "ㄎㄜˇ ㄧˇ ㄅㄤ ㄨㄛˇ ㄇㄚ",
    blank: { hint: "人", suggest: ["you","Mom","Dad","Teacher","he","she"] } },
  { week: 8,  en: "Can I go to the restroom?",          zh: "我可以去廁所嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄘㄜˋ ㄙㄨㄛˇ ㄇㄚ" },
  { week: 9,  en: "Can I go get some water?",           zh: "我可以去拿水嗎?",
    bopo: "ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄑㄩˋ ㄋㄚˊ ㄕㄨㄟˇ ㄇㄚ" },
  { week: 10, en: "Can ___ go with me?",                zh: "___可以跟我去嗎?",
    bopo: "ㄎㄜˇ ㄧˇ ㄍㄣ ㄨㄛˇ ㄑㄩˋ ㄇㄚ",
    blank: { hint: "人", suggest: ["you","he","she","Mom","Dad"] } },
  { week: 11, en: "Just a minute.",                     zh: "等一下",
    bopo: "ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ" },
  { week: 12, en: "I put it away.",                     zh: "我收起來了",
    bopo: "ㄨㄛˇ ㄕㄡ ㄑㄧˇ ㄌㄞˊ ㄌㄜ˙" },
  { week: 13, en: "Teacher, can I help you?",           zh: "老師，我可以幫你嗎?",
    bopo: "ㄌㄠˇ ㄕ ㄨㄛˇ ㄎㄜˇ ㄧˇ ㄅㄤ ㄋㄧˇ ㄇㄚ" },
  { week: 14, en: "I want to help!",                    zh: "我想要幫忙!",
    bopo: "ㄨㄛˇ ㄒㄧㄤˇ ㄧㄠˋ ㄅㄤ ㄇㄤˊ" },
  { week: 15, en: "I have a question.",                 zh: "我有一個問題",
    bopo: "ㄨㄛˇ ㄧㄡˇ ㄧˊ ㄍㄜ˙ ㄨㄣˋ ㄊㄧˊ" },
  { week: 16, en: "Where are we going?",                zh: "我們要去哪裡?",
    bopo: "ㄨㄛˇ ㄇㄣ˙ ㄧㄠˋ ㄑㄩˋ ㄋㄚˇ ㄌㄧˇ" },
  { week: 17, en: "Help, ___ hit me!",                  zh: "救命，___打我!",
    bopo: "ㄐㄧㄡˋ ㄇㄧㄥˋ ㄉㄚˇ ㄨㄛˇ",
    blank: { hint: "人", suggest: ["he","she","they","someone"] } },
  { week: 18, en: "He / She took my ___.",              zh: "他/她拿了我的___",
    bopo: "ㄊㄚ ㄊㄚ ㄋㄚˊ ㄌㄜ˙ ㄨㄛˇ ㄉㄜ˙",
    blank: { hint: "東西", suggest: ["pencil","book","bag","toy","game"] } },
  { week: 19, en: "It's not my fault.",                 zh: "不是我的錯",
    bopo: "ㄅㄨˊ ㄕˋ ㄨㄛˇ ㄉㄜ˙ ㄘㄨㄛˋ" },
  { week: 20, en: "I'm sorry. I didn't mean to ___.",   zh: "對不起，我不是故意___",
    bopo: "ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ ㄨㄛˇ ㄅㄨˊ ㄕˋ ㄍㄨˋ ㄧˋ",
    blank: { hint: "動作", suggest: ["do it","push you","break it","hurt you"] } },
];

const CATEGORIES = [
  { id: "toys",      name: "玩具",     bopo: "ㄨㄢˊ ㄐㄩˋ",          nameEn: "Toys",      emoji: "🧸", color: "#ffd6e0",
    words: ["bike","computer","game","teddy bear","robot","kite"] },
  { id: "colors",    name: "顏色",     bopo: "ㄧㄢˊ ㄙㄜˋ",          nameEn: "Colors",    emoji: "🎨", color: "#ffe5b4",
    words: ["red","blue","white","green","pink","gray","black","yellow","orange","brown"] },
  { id: "animals",   name: "動物",     bopo: "ㄉㄨㄥˋ ㄨˋ",          nameEn: "Animals",   emoji: "🐰", color: "#d0f4de",
    words: ["bird","rabbit","turtle","mouse","horse","snake","spider","frog","iguana","hamster"] },
  { id: "body",      name: "身體",     bopo: "ㄕㄣ ㄊㄧˇ",           nameEn: "Body",      emoji: "👀", color: "#fcd5ce",
    words: ["hair","mouth","eye","ear","nose","tooth/teeth","toe","finger","hand","foot/feet","arm","leg"] },
  { id: "places",    name: "地方",     bopo: "ㄉㄧˋ ㄈㄤ",           nameEn: "Places",    emoji: "🏫", color: "#cdeafe",
    words: ["school","mall","pool","stadium","lake","beach","park"] },
  { id: "nature",    name: "大自然",   bopo: "ㄉㄚˋ ㄗˋ ㄖㄢˊ",      nameEn: "Nature",    emoji: "🌳", color: "#b8e0d2",
    words: ["tree","river","mountain","flower"] },
  { id: "fruits",    name: "水果",     bopo: "ㄕㄨㄟˇ ㄍㄨㄛˇ",       nameEn: "Fruits",    emoji: "🍌", color: "#fff5ba",
    words: ["banana","watermelon","pineapple","pear"] },
  { id: "numbers",   name: "數字",     bopo: "ㄕㄨˋ ㄗˋ",           nameEn: "Numbers",   emoji: "🔢", color: "#e0c3fc",
    words: ["eleven","twelve","thirteen","fifteen","twenty"] },
  { id: "furniture", name: "家具",     bopo: "ㄐㄧㄚ ㄐㄩˋ",          nameEn: "Furniture", emoji: "🛏️", color: "#f5d0c5",
    words: ["bed","sofa","closet","chair","table"] },
  { id: "rooms",     name: "房間",     bopo: "ㄈㄤˊ ㄐㄧㄢ",          nameEn: "Rooms",     emoji: "🚪", color: "#c1e7e3",
    words: ["bedroom","bathroom","garage","yard","living room","kitchen"] },
];

// ADHD 友善 — 動一動小提示，每答對 N 題彈一次
const MOVEMENT_BREAKS = [
  { emoji: "🤸", text: "站起來跳 5 下！" },
  { emoji: "🙌", text: "雙手舉高，伸個懶腰～" },
  { emoji: "👏", text: "拍手 5 下，慶祝一下！" },
  { emoji: "🦵", text: "原地踏步 10 下！" },
  { emoji: "🌬️", text: "深呼吸 3 次：吸～呼～" },
  { emoji: "💃", text: "扭一扭屁股 10 秒！" },
  { emoji: "👀", text: "眼睛左右轉，看看遠方～" },
  { emoji: "🤲", text: "把手搓熱，蓋住眼睛 5 秒" },
];

// 介面中文逐字注音對照表 — 用於 rubyEl 自動查表
// 多音字採介面語境最常見讀音；若實際語境需要不同讀音，外層用人工 bopo 覆蓋
const CHAR_BOPO = {
  // 數字 / 量詞 / 通用
  "一": "ㄧ", "二": "ㄦˋ", "三": "ㄙㄢ", "四": "ㄙˋ", "五": "ㄨˇ",
  "六": "ㄌㄧㄡˋ", "七": "ㄑㄧ", "八": "ㄅㄚ", "九": "ㄐㄧㄡˇ", "十": "ㄕˊ",
  "個": "ㄍㄜ˙", "次": "ㄘˋ", "顆": "ㄎㄜ", "張": "ㄓㄤ", "共": "ㄍㄨㄥˋ",
  "份": "ㄈㄣˋ", "些": "ㄒㄧㄝ", "點": "ㄉㄧㄢˇ", "片": "ㄆㄧㄢˋ", "本": "ㄅㄣˇ",
  "頁": "ㄧㄝˋ", "秒": "ㄇㄧㄠˇ", "分": "ㄈㄣ",
  // 代名詞 / 助詞
  "我": "ㄨㄛˇ", "你": "ㄋㄧˇ", "他": "ㄊㄚ", "她": "ㄊㄚ", "它": "ㄊㄚ",
  "們": "ㄇㄣ˙", "誰": "ㄕㄟˊ", "哪": "ㄋㄚˇ", "什": "ㄕㄜˊ", "麼": "ㄇㄜ˙",
  "的": "ㄉㄜ˙", "了": "ㄌㄜ˙", "在": "ㄗㄞˋ", "是": "ㄕˋ", "有": "ㄧㄡˇ",
  "沒": "ㄇㄟˊ", "不": "ㄅㄨˋ", "也": "ㄧㄝˇ", "都": "ㄉㄡ", "和": "ㄏㄜˊ",
  "或": "ㄏㄨㄛˋ", "跟": "ㄍㄣ", "把": "ㄅㄚˇ", "從": "ㄘㄨㄥˊ", "之": "ㄓ",
  "為": "ㄨㄟˋ", "因": "ㄧㄣ", "若": "ㄖㄨㄛˋ", "啊": "ㄚ", "呀": "ㄧㄚ˙",
  "呢": "ㄋㄜ˙", "嗎": "ㄇㄚ", "吧": "ㄅㄚ˙", "喔": "ㄛ", "好": "ㄏㄠˇ",
  "可": "ㄎㄜˇ", "以": "ㄧˇ", "要": "ㄧㄠˋ", "想": "ㄒㄧㄤˇ", "會": "ㄏㄨㄟˋ",
  "能": "ㄋㄥˊ", "等": "ㄉㄥˇ", "已": "ㄧˇ", "再": "ㄗㄞˋ", "又": "ㄧㄡˋ",
  // 動作 / 學習
  "看": "ㄎㄢˋ", "聽": "ㄊㄧㄥ", "說": "ㄕㄨㄛ", "讀": "ㄉㄨˊ", "念": "ㄋㄧㄢˋ",
  "寫": "ㄒㄧㄝˇ", "畫": "ㄏㄨㄚˋ", "選": "ㄒㄩㄢˇ", "答": "ㄉㄚˊ", "對": "ㄉㄨㄟˋ",
  "錯": "ㄘㄨㄛˋ", "練": "ㄌㄧㄢˋ", "習": "ㄒㄧˊ", "學": "ㄒㄩㄝˊ", "教": "ㄐㄧㄠ",
  "做": "ㄗㄨㄛˋ", "玩": "ㄨㄢˊ", "送": "ㄙㄨㄥˋ", "拿": "ㄋㄚˊ", "拼": "ㄆㄧㄣ",
  "指": "ㄓˇ", "描": "ㄇㄧㄠˊ", "提": "ㄊㄧˊ", "換": "ㄏㄨㄢˋ", "擇": "ㄗㄜˊ",
  "切": "ㄑㄧㄝ", "按": "ㄢˋ", "拍": "ㄆㄞ", "跳": "ㄊㄧㄠˋ",
  "走": "ㄗㄡˇ", "去": "ㄑㄩˋ", "來": "ㄌㄞˊ", "回": "ㄏㄨㄟˊ", "進": "ㄐㄧㄣˋ",
  "出": "ㄔㄨ", "入": "ㄖㄨˋ", "上": "ㄕㄤˋ", "下": "ㄒㄧㄚˋ", "找": "ㄓㄠˇ",
  "取": "ㄑㄩˇ", "查": "ㄔㄚˊ", "判": "ㄆㄢˋ", "斷": "ㄉㄨㄢˋ", "輸": "ㄕㄨ",
  "贏": "ㄧㄥˊ", "完": "ㄨㄢˊ", "成": "ㄔㄥˊ", "始": "ㄕˇ", "開": "ㄎㄞ",
  "關": "ㄍㄨㄢ", "閉": "ㄅㄧˋ", "幫": "ㄅㄤ", "忙": "ㄇㄤˊ", "助": "ㄓㄨˋ",
  "歡": "ㄏㄨㄢ", "迎": "ㄧㄥˊ", "繼": "ㄐㄧˋ", "續": "ㄒㄩˋ",
  "覺": "ㄐㄩㄝˊ", "得": "ㄉㄜ˙", "問": "ㄨㄣˋ", "祝": "ㄓㄨˋ", "慶": "ㄑㄧㄥˋ",
  // 學習相關名詞
  "字": "ㄗˋ", "詞": "ㄘˊ", "句": "ㄐㄩˋ", "子": "ㄗ˙", "卡": "ㄎㄚˇ",
  "首": "ㄕㄡˇ", "頭": "ㄊㄡˊ", "課": "ㄎㄜˋ", "週": "ㄓㄡ",
  "天": "ㄊㄧㄢ", "今": "ㄐㄧㄣ", "昨": "ㄗㄨㄛˊ", "明": "ㄇㄧㄥˊ", "日": "ㄖˋ",
  "月": "ㄩㄝˋ", "年": "ㄋㄧㄢˊ", "時": "ㄕˊ", "間": "ㄐㄧㄢ", "期": "ㄑㄧˊ",
  "度": "ㄉㄨˋ", "考": "ㄎㄠˇ", "試": "ㄕˋ", "驗": "ㄧㄢˋ", "題": "ㄊㄧˊ",
  "目": "ㄇㄨˋ", "數": "ㄕㄨˋ", "星": "ㄒㄧㄥ", "總": "ㄗㄨㄥˇ", "覽": "ㄌㄢˇ",
  "詳": "ㄒㄧㄤˊ", "情": "ㄑㄧㄥˊ", "最": "ㄗㄨㄟˋ", "後": "ㄏㄡˋ", "前": "ㄑㄧㄢˊ",
  "使": "ㄕˇ", "用": "ㄩㄥˋ", "需": "ㄒㄩ", "加": "ㄐㄧㄚ", "強": "ㄑㄧㄤˊ",
  "紀": "ㄐㄧˋ", "錄": "ㄌㄨˋ", "列": "ㄌㄧㄝˋ", "表": "ㄅㄧㄠˇ", "單": "ㄉㄢ",
  "元": "ㄩㄢˊ", "主": "ㄓㄨˇ", "依": "ㄧ", "正": "ㄓㄥˋ", "確": "ㄑㄩㄝˋ",
  "案": "ㄢˋ", "示": "ㄕˋ", "音": "ㄧㄣ", "效": "ㄒㄧㄠˋ", "聲": "ㄕㄥ",
  "喇": "ㄌㄚˇ", "叭": "ㄅㄚ", "填": "ㄊㄧㄢˊ", "空": "ㄎㄨㄥ", "全": "ㄑㄩㄢˊ",
  "部": "ㄅㄨˋ", "新": "ㄒㄧㄣ", "增": "ㄗㄥ", "刪": "ㄕㄢ", "除": "ㄔㄨˊ",
  "重": "ㄔㄨㄥˊ", "設": "ㄕㄜˋ", "母": "ㄇㄨˇ", "輪": "ㄌㄨㄣˊ",
  // 介面 / 副詞 / 形容詞
  "棒": "ㄅㄤˋ", "油": "ㄧㄡˊ", "中": "ㄓㄨㄥ", "文": "ㄨㄣˊ", "英": "ㄧㄥ",
  "語": "ㄩˇ", "這": "ㄓㄜˋ", "那": "ㄋㄚˋ", "裡": "ㄌㄧˇ", "邊": "ㄅㄧㄢ",
  "處": "ㄔㄨˋ", "每": "ㄇㄟˇ", "各": "ㄍㄜˋ", "別": "ㄅㄧㄝˊ", "種": "ㄓㄨㄥˇ",
  "類": "ㄌㄟˋ", "群": "ㄑㄩㄣˊ", "組": "ㄗㄨˇ", "集": "ㄐㄧˊ", "合": "ㄏㄜˊ",
  "無": "ㄨˊ", "然": "ㄖㄢˊ", "熟": "ㄕㄡˊ", "白": "ㄅㄞˊ", "底": "ㄉㄧˇ",
  "至": "ㄓˋ", "者": "ㄓㄜˇ", "資": "ㄗ", "料": "ㄌㄧㄠˋ", "清": "ㄑㄧㄥ",
  "測": "ㄘㄜˋ", "勾": "ㄍㄡ", "可": "ㄎㄜˇ", "多": "ㄉㄨㄛ", "工": "ㄍㄨㄥ",
  "具": "ㄐㄩˋ", "再": "ㄗㄞˋ", "縮": "ㄙㄨㄛ", "放": "ㄈㄤˋ", "大": "ㄉㄚˋ",
  "小": "ㄒㄧㄠˇ", "專": "ㄓㄨㄢ", "結": "ㄐㄧㄝˊ", "果": "ㄍㄨㄛˇ", "績": "ㄐㄧ",
  "百": "ㄅㄞˇ", "比": "ㄅㄧˇ", "例": "ㄌㄧˋ", "率": "ㄌㄩˋ", "平": "ㄆㄧㄥˊ",
  "均": "ㄐㄩㄣ", "報": "ㄅㄠˋ", "告": "ㄍㄠˋ", "警": "ㄐㄧㄥˇ", "意": "ㄧˋ",
  "注": "ㄓㄨˋ", "張": "ㄓㄤ", "力": "ㄌㄧˋ", "些": "ㄒㄧㄝ", "原": "ㄩㄢˊ",
  "地": "ㄉㄧˋ", "踏": "ㄊㄚˋ", "步": "ㄅㄨˋ", "深": "ㄕㄣ", "呼": "ㄏㄨ",
  "吸": "ㄒㄧ", "扭": "ㄋㄧㄡˇ", "屁": "ㄆㄧˋ", "股": "ㄍㄨˇ", "眼": "ㄧㄢˇ",
  "睛": "ㄐㄧㄥ", "左": "ㄗㄨㄛˇ", "右": "ㄧㄡˋ", "轉": "ㄓㄨㄢˇ", "遠": "ㄩㄢˇ",
  "搓": "ㄘㄨㄛ", "熱": "ㄖㄜˋ", "蓋": "ㄍㄞˋ", "住": "ㄓㄨˋ", "舉": "ㄐㄩˇ",
  "雙": "ㄕㄨㄤ", "高": "ㄍㄠ", "伸": "ㄕㄣ", "懶": "ㄌㄢˇ", "腰": "ㄧㄠ",
  "腳": "ㄐㄧㄠˇ", "站": "ㄓㄢˋ", "起": "ㄑㄧˇ", "立": "ㄌㄧˋ",
  // 家長模式
  "家": "ㄐㄧㄚ", "長": "ㄓㄤˇ", "模": "ㄇㄛˊ", "式": "ㄕˋ", "請": "ㄑㄧㄥˇ",
  "位": "ㄨㄟˋ", "認": "ㄖㄣˋ", "忘": "ㄨㄤˋ", "記": "ㄐㄧˋ", "鎖": "ㄙㄨㄛˇ",
  "定": "ㄉㄧㄥˋ", "登": "ㄉㄥ", "戶": "ㄏㄨˋ", "用": "ㄩㄥˋ",
  // 補充
  "司": "ㄙ", "司": "ㄙ", "口": "ㄎㄡˇ", "中": "ㄓㄨㄥ", "心": "ㄒㄧㄣ",
  "色": "ㄙㄜˋ", "故": "ㄍㄨˋ", "意": "ㄧˋ", "錯": "ㄘㄨㄛˋ", "面": "ㄇㄧㄢˋ",
  "圖": "ㄊㄨˊ", "片": "ㄆㄧㄢˋ", "辦": "ㄅㄢˋ", "法": "ㄈㄚˇ",
  "分": "ㄈㄣ", "鐘": "ㄓㄨㄥ", "個": "ㄍㄜ˙", "隔": "ㄍㄜˊ",
};
