// 再興小學一年級上學期 (115-1 / 2026 Fall) 英文單字 + 注音
// 資料來源：學校單字表 PDF「115-1 G1 單字表」(Next Move 1)
// 第 1-2 週為字母（PDF 每格 4 個字母，這裡拆成一個字母一張卡）；第 3 週「(your name)」是填自己名字，不列入
// bopo 欄位：每個漢字一段注音（空白分隔）

const GRADE1 = (() => {
  const WORDS = {
    "Aa"            : { zh: "字母 A", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🍎", category: "letters", speak: "A" },
    "Bb"            : { zh: "字母 B", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐻", category: "letters", speak: "B" },
    "Cc"            : { zh: "字母 C", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐱", category: "letters", speak: "C" },
    "Dd"            : { zh: "字母 D", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐶", category: "letters", speak: "D" },
    "Ee"            : { zh: "字母 E", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🥚", category: "letters", speak: "E" },
    "Ff"            : { zh: "字母 F", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐟", category: "letters", speak: "F" },
    "Gg"            : { zh: "字母 G", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🍇", category: "letters", speak: "G" },
    "Hh"            : { zh: "字母 H", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🎩", category: "letters", speak: "H" },
    "Ii"            : { zh: "字母 I", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🍦", category: "letters", speak: "I" },
    "Jj"            : { zh: "字母 J", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🧃", category: "letters", speak: "J" },
    "Kk"            : { zh: "字母 K", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🪁", category: "letters", speak: "K" },
    "Ll"            : { zh: "字母 L", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🦁", category: "letters", speak: "L" },
    "Mm"            : { zh: "字母 M", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐵", category: "letters", speak: "M" },
    "Nn"            : { zh: "字母 N", bopo: "ㄗˋ ㄇㄨˇ", emoji: "👃", category: "letters", speak: "N" },
    "Oo"            : { zh: "字母 O", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐙", category: "letters", speak: "O" },
    "Pp"            : { zh: "字母 P", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐷", category: "letters", speak: "P" },
    "Qq"            : { zh: "字母 Q", bopo: "ㄗˋ ㄇㄨˇ", emoji: "👑", category: "letters", speak: "Q" },
    "Rr"            : { zh: "字母 R", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐰", category: "letters", speak: "R" },
    "Ss"            : { zh: "字母 S", bopo: "ㄗˋ ㄇㄨˇ", emoji: "☀️", category: "letters", speak: "S" },
    "Tt"            : { zh: "字母 T", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🐯", category: "letters", speak: "T" },
    "Uu"            : { zh: "字母 U", bopo: "ㄗˋ ㄇㄨˇ", emoji: "☂️", category: "letters", speak: "U" },
    "Vv"            : { zh: "字母 V", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🎻", category: "letters", speak: "V" },
    "Ww"            : { zh: "字母 W", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🍉", category: "letters", speak: "W" },
    "Xx"            : { zh: "字母 X", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🩻", category: "letters", speak: "X" },
    "Yy"            : { zh: "字母 Y", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🪀", category: "letters", speak: "Y" },
    "Zz"            : { zh: "字母 Z", bopo: "ㄗˋ ㄇㄨˇ", emoji: "🦓", category: "letters", speak: "Z" },
    "Hi"            : { zh: "嗨", bopo: "ㄏㄞ", emoji: "👋", category: "greet" },
    "Hello"         : { zh: "你好", bopo: "ㄋㄧˇ ㄏㄠˇ", emoji: "🙋", category: "greet" },
    "name"          : { zh: "名字", bopo: "ㄇㄧㄥˊ ㄗˋ", emoji: "📛", category: "greet" },
    "school"        : { zh: "學校", bopo: "ㄒㄩㄝˊ ㄒㄧㄠˋ", emoji: "🏫", category: "classroom" },
    "class"         : { zh: "班級", bopo: "ㄅㄢ ㄐㄧˊ", emoji: "🧑\u200d🏫", category: "classroom" },
    "classroom"     : { zh: "教室", bopo: "ㄐㄧㄠˋ ㄕˋ", emoji: "🏫", category: "classroom" },
    "board"         : { zh: "黑板", bopo: "ㄏㄟ ㄅㄢˇ", emoji: "🟩", category: "classroom" },
    "map"           : { zh: "地圖", bopo: "ㄉㄧˋ ㄊㄨˊ", emoji: "🗺️", category: "classroom" },
    "clock"         : { zh: "時鐘", bopo: "ㄕˊ ㄓㄨㄥ", emoji: "🕐", category: "classroom" },
    "table"         : { zh: "桌子", bopo: "ㄓㄨㄛ ㄗ˙", emoji: "🪑", category: "classroom" },
    "computer"      : { zh: "電腦", bopo: "ㄉㄧㄢˋ ㄋㄠˇ", emoji: "💻", category: "classroom" },
    "pen"           : { zh: "原子筆", bopo: "ㄩㄢˊ ㄗˇ ㄅㄧˇ", emoji: "🖊️", category: "supplies" },
    "pencil"        : { zh: "鉛筆", bopo: "ㄑㄧㄢ ㄅㄧˇ", emoji: "✏️", category: "supplies" },
    "eraser"        : { zh: "橡皮擦", bopo: "ㄒㄧㄤˋ ㄆㄧˊ ㄘㄚ", emoji: "🧽", category: "supplies" },
    "crayon"        : { zh: "蠟筆", bopo: "ㄌㄚˋ ㄅㄧˇ", emoji: "🖍️", category: "supplies" },
    "paper"         : { zh: "紙", bopo: "ㄓˇ", emoji: "📄", category: "supplies" },
    "picture"       : { zh: "圖畫", bopo: "ㄊㄨˊ ㄏㄨㄚˋ", emoji: "🖼️", category: "supplies" },
    "color"         : { zh: "顏色", bopo: "ㄧㄢˊ ㄙㄜˋ", emoji: "🌈", category: "supplies" },
    "number"        : { zh: "數字", bopo: "ㄕㄨˋ ㄗˋ", emoji: "🔢", category: "supplies" },
    "world"         : { zh: "世界", bopo: "ㄕˋ ㄐㄧㄝˋ", emoji: "🌍", category: "nature" },
    "sky"           : { zh: "天空", bopo: "ㄊㄧㄢ ㄎㄨㄥ", emoji: "🌤️", category: "nature" },
    "mountain"      : { zh: "山", bopo: "ㄕㄢ", emoji: "⛰️", category: "nature" },
    "tree"          : { zh: "樹", bopo: "ㄕㄨˋ", emoji: "🌳", category: "nature" },
    "grass"         : { zh: "草", bopo: "ㄘㄠˇ", emoji: "🌱", category: "nature" },
    "rock"          : { zh: "石頭", bopo: "ㄕˊ ㄊㄡ˙", emoji: "🪨", category: "nature" },
    "river"         : { zh: "河", bopo: "ㄏㄜˊ", emoji: "🏞️", category: "nature" },
    "ocean"         : { zh: "海洋", bopo: "ㄏㄞˇ ㄧㄤˊ", emoji: "🌊", category: "nature" },
    "sun"           : { zh: "太陽", bopo: "ㄊㄞˋ ㄧㄤˊ", emoji: "☀️", category: "nature" },
    "moon"          : { zh: "月亮", bopo: "ㄩㄝˋ ㄌㄧㄤˋ", emoji: "🌙", category: "nature" },
    "star"          : { zh: "星星", bopo: "ㄒㄧㄥ ㄒㄧㄥ", emoji: "⭐", category: "nature" },
    "cloud"         : { zh: "雲", bopo: "ㄩㄣˊ", emoji: "☁️", category: "nature" },
    "bush"          : { zh: "灌木叢", bopo: "ㄍㄨㄢˋ ㄇㄨˋ ㄘㄨㄥˊ", emoji: "🌿", category: "nature" },
    "flower"        : { zh: "花", bopo: "ㄏㄨㄚ", emoji: "🌸", category: "nature" },
    "bird"          : { zh: "鳥", bopo: "ㄋㄧㄠˇ", emoji: "🐦", category: "nature" },
    "butterfly"     : { zh: "蝴蝶", bopo: "ㄏㄨˊ ㄉㄧㄝˊ", emoji: "🦋", category: "nature" },
    "family"        : { zh: "家人", bopo: "ㄐㄧㄚ ㄖㄣˊ", emoji: "👨\u200d👩\u200d👧", category: "family" },
    "photo"         : { zh: "照片", bopo: "ㄓㄠˋ ㄆㄧㄢˋ", emoji: "📷", category: "family" },
    "parents"       : { zh: "父母", bopo: "ㄈㄨˋ ㄇㄨˇ", emoji: "👫", category: "family" },
    "father"        : { zh: "爸爸", bopo: "ㄅㄚˋ ㄅㄚ˙", emoji: "👨", category: "family" },
    "mother"        : { zh: "媽媽", bopo: "ㄇㄚ ㄇㄚ˙", emoji: "👩", category: "family" },
    "brother"       : { zh: "哥哥、弟弟", bopo: "ㄍㄜ ㄍㄜ˙ ㄉㄧˋ ㄉㄧ˙", emoji: "👦", category: "family" },
    "sister"        : { zh: "姊姊、妹妹", bopo: "ㄐㄧㄝˇ ㄐㄧㄝ˙ ㄇㄟˋ ㄇㄟ˙", emoji: "👧", category: "family" },
    "baby"          : { zh: "寶寶", bopo: "ㄅㄠˇ ㄅㄠ˙", emoji: "👶", category: "family" },
    "grandma"       : { zh: "奶奶、外婆", bopo: "ㄋㄞˇ ㄋㄞ˙ ㄨㄞˋ ㄆㄛˊ", emoji: "👵", category: "family" },
    "grandpa"       : { zh: "爺爺、外公", bopo: "ㄧㄝˊ ㄧㄝ˙ ㄨㄞˋ ㄍㄨㄥ", emoji: "👴", category: "family" },
    "old"           : { zh: "老的", bopo: "ㄌㄠˇ ㄉㄜ˙", emoji: "🧓", category: "describe" },
    "young"         : { zh: "年輕的", bopo: "ㄋㄧㄢˊ ㄑㄧㄥ ㄉㄜ˙", emoji: "🧒", category: "describe" },
    "tall"          : { zh: "高的", bopo: "ㄍㄠ ㄉㄜ˙", emoji: "🦒", category: "describe" },
    "short"         : { zh: "矮的", bopo: "ㄞˇ ㄉㄜ˙", emoji: "🐜", category: "describe" },
    "small"         : { zh: "小的", bopo: "ㄒㄧㄠˇ ㄉㄜ˙", emoji: "🐭", category: "describe" },
    "big"           : { zh: "大的", bopo: "ㄉㄚˋ ㄉㄜ˙", emoji: "🐘", category: "describe" },
    "house"         : { zh: "房子", bopo: "ㄈㄤˊ ㄗ˙", emoji: "🏠", category: "home" },
    "bed"           : { zh: "床", bopo: "ㄔㄨㄤˊ", emoji: "🛏️", category: "home" },
    "sofa"          : { zh: "沙發", bopo: "ㄕㄚ ㄈㄚ", emoji: "🛋️", category: "home" },
    "lamp"          : { zh: "檯燈", bopo: "ㄊㄞˊ ㄉㄥ", emoji: "💡", category: "home" },
    "mirror"        : { zh: "鏡子", bopo: "ㄐㄧㄥˋ ㄗ˙", emoji: "🪞", category: "home" },
    "bedroom"       : { zh: "臥室", bopo: "ㄨㄛˋ ㄕˋ", emoji: "🛌", category: "home" },
    "bathroom"      : { zh: "浴室", bopo: "ㄩˋ ㄕˋ", emoji: "🚿", category: "home" },
    "kitchen"       : { zh: "廚房", bopo: "ㄔㄨˊ ㄈㄤˊ", emoji: "🍳", category: "home" },
    "living room"   : { zh: "客廳", bopo: "ㄎㄜˋ ㄊㄧㄥ", emoji: "🛋️", category: "home" },
    "dining room"   : { zh: "餐廳", bopo: "ㄘㄢ ㄊㄧㄥ", emoji: "🍽️", category: "home" },
    "eating"        : { zh: "吃東西", bopo: "ㄔ ㄉㄨㄥ ㄒㄧ˙", emoji: "🍚", category: "actions" },
    "sleeping"      : { zh: "睡覺", bopo: "ㄕㄨㄟˋ ㄐㄧㄠˋ", emoji: "😴", category: "actions" },
    "cooking"       : { zh: "煮飯", bopo: "ㄓㄨˇ ㄈㄢˋ", emoji: "🧑\u200d🍳", category: "actions" },
    "cleaning"      : { zh: "打掃", bopo: "ㄉㄚˇ ㄙㄠˇ", emoji: "🧹", category: "actions" },
    "watching TV"   : { zh: "看電視", bopo: "ㄎㄢˋ ㄉㄧㄢˋ ㄕˋ", emoji: "📺", category: "actions" },
    "taking a bath" : { zh: "洗澡", bopo: "ㄒㄧˇ ㄗㄠˇ", emoji: "🛁", category: "actions" },
  };

  const WEEKS = [
    { num: 1, dateRange: "8/31-9/5", start: "2026-08-31", end: "2026-09-05", progress: "The Alphabet Aa-Nn", words: ["Aa","Bb","Cc","Dd","Ee","Ff","Gg","Hh","Ii","Jj","Kk","Ll","Mm","Nn"] },
    { num: 2, dateRange: "9/6-9/12", start: "2026-09-06", end: "2026-09-12", progress: "The Alphabet Oo-Zz", words: ["Oo","Pp","Qq","Rr","Ss","Tt","Uu","Vv","Ww","Xx","Yy","Zz"] },
    { num: 3, dateRange: "9/13-9/19", start: "2026-09-13", end: "2026-09-19", progress: "Review Aa-Zz・Unit 0", words: ["Hi","Hello","name"] },
    { num: 4, dateRange: "9/20-9/26", start: "2026-09-20", end: "2026-09-26", progress: "Unit 1", words: ["school","class","classroom","board"] },
    { num: 5, dateRange: "9/27-10/3", start: "2026-09-27", end: "2026-10-03", progress: "Unit 1", words: ["map","clock","table","computer"] },
    { num: 6, dateRange: "10/4-10/10", start: "2026-10-04", end: "2026-10-10", progress: "Unit 1", words: ["pen","pencil","eraser","crayon"] },
    { num: 7, dateRange: "10/11-10/17", start: "2026-10-11", end: "2026-10-17", progress: "Unit 1 Quiz 1", words: ["paper","picture","color","number"] },
    { num: 8, dateRange: "10/18-10/24", start: "2026-10-18", end: "2026-10-24", progress: "Unit 2", words: ["world","sky","mountain","tree"] },
    { num: 9, dateRange: "10/25-10/31", start: "2026-10-25", end: "2026-10-31", progress: "Unit 2", words: ["grass","rock","river","ocean"] },
    { num: 10, dateRange: "11/1-11/7", start: "2026-11-01", end: "2026-11-07", progress: "Unit 2", words: ["sun","moon","star","cloud"] },
    { num: 11, dateRange: "11/8-11/14", start: "2026-11-08", end: "2026-11-14", progress: "Unit 2 Quiz 2", words: ["bush","flower","bird","butterfly"] },
    { num: 12, dateRange: "11/15-11/21", start: "2026-11-15", end: "2026-11-21", progress: "Unit 3", words: ["family","photo","parents","father"] },
    { num: 13, dateRange: "11/22-11/28", start: "2026-11-22", end: "2026-11-28", progress: "Unit 3", words: ["mother","brother","sister","baby"] },
    { num: 14, dateRange: "11/29-12/5", start: "2026-11-29", end: "2026-12-05", progress: "Unit 3", words: ["grandma","grandpa","old","young"] },
    { num: 15, dateRange: "12/6-12/12", start: "2026-12-06", end: "2026-12-12", progress: "Unit 3 Quiz 3", words: ["tall","short","small","big"] },
    { num: 16, dateRange: "12/13-12/19", start: "2026-12-13", end: "2026-12-19", progress: "Unit 4", words: ["house","bed","sofa","lamp"] },
    { num: 17, dateRange: "12/20-12/26", start: "2026-12-20", end: "2026-12-26", progress: "Unit 4", words: ["mirror","bedroom","bathroom","kitchen"] },
    { num: 18, dateRange: "12/27-1/2", start: "2026-12-27", end: "2027-01-02", progress: "Unit 4", words: ["living room","dining room","eating","sleeping"] },
    { num: 19, dateRange: "1/3-1/9", start: "2027-01-03", end: "2027-01-09", progress: "Unit 4 Quiz 4", words: ["cooking","cleaning","watching TV","taking a bath"] },
    { num: 20, dateRange: "1/10-1/16", start: "2027-01-10", end: "2027-01-16", progress: "Final (Unit 1-4)", words: [] },
    { num: 21, dateRange: "1/17-1/20", start: "2027-01-17", end: "2027-01-20", progress: "Review (Unit 1-4)", words: [] },
  ];

  const weeksWords = (...nums) => nums.flatMap(n => WEEKS.find(w => w.num === n).words);
  const UNITS = [
    { id: "abc", name: "字母 A-Z", emoji: "🔤", color: "#e0c3fc", words: weeksWords(1, 2) },
    { id: "unit-0", name: "Unit 0 打招呼", emoji: "👋", color: "#ffd6e0", words: weeksWords(3) },
    { id: "unit-1", name: "Unit 1 教室·學用品", emoji: "🏫", color: "#ffe5b4", words: weeksWords(4, 5, 6, 7) },
    { id: "unit-2", name: "Unit 2 大自然", emoji: "🌳", color: "#d0f4de", words: weeksWords(8, 9, 10, 11) },
    { id: "unit-3", name: "Unit 3 家人·形容", emoji: "👨‍👩‍👧", color: "#cdeafe", words: weeksWords(12, 13, 14, 15) },
    { id: "unit-4", name: "Unit 4 家裡·活動", emoji: "🏠", color: "#fcd5ce", words: weeksWords(16, 17, 18, 19) },
  ];

  // 每週一句：115-1 一年級單字表沒有每週一句
  const SENTENCES = [];

  const CATEGORIES = [
    { id: "letters", name: "字母", bopo: "ㄗˋ ㄇㄨˇ", nameEn: "Letters", emoji: "🔤", color: "#e0c3fc" },
    { id: "greet", name: "打招呼", bopo: "ㄉㄚˇ ㄓㄠ ㄏㄨ", nameEn: "Hello", emoji: "👋", color: "#ffd6e0" },
    { id: "classroom", name: "教室", bopo: "ㄐㄧㄠˋ ㄕˋ", nameEn: "Classroom", emoji: "🏫", color: "#ffe5b4" },
    { id: "supplies", name: "學用品", bopo: "ㄒㄩㄝˊ ㄩㄥˋ ㄆㄧㄣˇ", nameEn: "Supplies", emoji: "✏️", color: "#fff5ba" },
    { id: "nature", name: "大自然", bopo: "ㄉㄚˋ ㄗˋ ㄖㄢˊ", nameEn: "Nature", emoji: "🌳", color: "#d0f4de" },
    { id: "family", name: "家人", bopo: "ㄐㄧㄚ ㄖㄣˊ", nameEn: "Family", emoji: "👨‍👩‍👧", color: "#cdeafe" },
    { id: "describe", name: "形容", bopo: "ㄒㄧㄥˊ ㄖㄨㄥˊ", nameEn: "Describe", emoji: "📏", color: "#e0e0e0" },
    { id: "home", name: "家裡", bopo: "ㄐㄧㄚ ㄌㄧˇ", nameEn: "Home", emoji: "🏠", color: "#fcd5ce" },
    { id: "actions", name: "在家做的事", bopo: "ㄗㄞˋ ㄐㄧㄚ ㄗㄨㄛˋ ㄉㄜ˙ ㄕˋ", nameEn: "At Home", emoji: "🧹", color: "#c1e7e3" },
  ].map(c => ({ ...c, words: Object.keys(WORDS).filter(w => WORDS[w].category === c.id) }));

  return { WORDS, WEEKS, UNITS, SENTENCES, CATEGORIES };
})();
